### ISSUE TITLE
Modify text input on response form to expand as user types

### ISSUE THREAD

**Issue by seanmetzgar** [ClickPop/backtalk-ui#22]
Utilizing `contentEditable` and `role="input"` on a div or span, create an expanding text field to mimic functionality in iMessage / Messenger apps

- Height should be limited to 3-4 rows of text
- When attempting it, LONG string (ones that filled the whole width) pushed the width of the input wider than the allotted space.

**Comment by GV14982** [comment]
Resolved with #28
