### ISSUE TITLE
Add map showing response locations

### ISSUE THREAD

**Issue by cvasquez** [ClickPop/backtalk-ui#64]
Add a map to the top of the responses feed for an individual survey that shows where respondents are coming from.

Ideally, you could save an image of your map, with Backtalk branding.

**Comment by GV14982** [comment]
I'll give this a shot.

**Comment by cvasquez** [comment]
Closing this with no link to a PR because @GV14982 merged directly to Develop like a [renegade](https://www.youtube.com/watch?v=NvlAor2ONsc).

**Comment by seanmetzgar** [comment]
@GV14982 you monster!!!
